# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment_censor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omment_censor.proto\x12\x0e\x63omment_censor\";\n\x14\x43ommentCensorRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\":\n\x12ImageCensorRequest\x12\x10\n\x08\x62\x61se_url\x18\x01 \x01(\t\x12\x12\n\nmedia_type\x18\x02 \x01(\t\"/\n\x15\x43ommentCensorResponse\x12\x16\n\x0e\x63\x65nsor_content\x18\x01 \x01(\t\"3\n\x13ImageCensorResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\xca\x01\n\x14\x43ommentCensorService\x12[\n\x0c\x43heckComment\x12$.comment_censor.CommentCensorRequest\x1a%.comment_censor.CommentCensorResponse\x12U\n\nCheckImage\x12\".comment_censor.ImageCensorRequest\x1a#.comment_censor.ImageCensorResponseb\x06proto3')



_COMMENTCENSORREQUEST = DESCRIPTOR.message_types_by_name['CommentCensorRequest']
_IMAGECENSORREQUEST = DESCRIPTOR.message_types_by_name['ImageCensorRequest']
_COMMENTCENSORRESPONSE = DESCRIPTOR.message_types_by_name['CommentCensorResponse']
_IMAGECENSORRESPONSE = DESCRIPTOR.message_types_by_name['ImageCensorResponse']
CommentCensorRequest = _reflection.GeneratedProtocolMessageType('CommentCensorRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTCENSORREQUEST,
  '__module__' : 'comment_censor_pb2'
  # @@protoc_insertion_point(class_scope:comment_censor.CommentCensorRequest)
  })
_sym_db.RegisterMessage(CommentCensorRequest)

ImageCensorRequest = _reflection.GeneratedProtocolMessageType('ImageCensorRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECENSORREQUEST,
  '__module__' : 'comment_censor_pb2'
  # @@protoc_insertion_point(class_scope:comment_censor.ImageCensorRequest)
  })
_sym_db.RegisterMessage(ImageCensorRequest)

CommentCensorResponse = _reflection.GeneratedProtocolMessageType('CommentCensorResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMENTCENSORRESPONSE,
  '__module__' : 'comment_censor_pb2'
  # @@protoc_insertion_point(class_scope:comment_censor.CommentCensorResponse)
  })
_sym_db.RegisterMessage(CommentCensorResponse)

ImageCensorResponse = _reflection.GeneratedProtocolMessageType('ImageCensorResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECENSORRESPONSE,
  '__module__' : 'comment_censor_pb2'
  # @@protoc_insertion_point(class_scope:comment_censor.ImageCensorResponse)
  })
_sym_db.RegisterMessage(ImageCensorResponse)

_COMMENTCENSORSERVICE = DESCRIPTOR.services_by_name['CommentCensorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMENTCENSORREQUEST._serialized_start=40
  _COMMENTCENSORREQUEST._serialized_end=99
  _IMAGECENSORREQUEST._serialized_start=101
  _IMAGECENSORREQUEST._serialized_end=159
  _COMMENTCENSORRESPONSE._serialized_start=161
  _COMMENTCENSORRESPONSE._serialized_end=208
  _IMAGECENSORRESPONSE._serialized_start=210
  _IMAGECENSORRESPONSE._serialized_end=261
  _COMMENTCENSORSERVICE._serialized_start=264
  _COMMENTCENSORSERVICE._serialized_end=466
# @@protoc_insertion_point(module_scope)
